install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restor src\NServiceBus.MongoDB.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: src\NServiceBus.MongoDB.sln
